# Generated by Django 3.2.22 on 2023-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../def_pic_f4egsp', upload_to='images/'),
        ),
    ]
